---
- name: delete snaphot vm
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yaml
  tasks:
    - name: delete snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item }}"
        state: absent
        snapshot_name: "ansible-snapshot"
        folder: "{{ vm_folder }}"
      with_items: "{{ vm_name }}"
...
