---
- name: configure time
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars-2.yml
  collections:
    - vmware.vmware_rest
  tasks:
    - name: Use the UTC timezone
      vmware.vmware_rest.appliance_system_time_timezone:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
        name: UTC
    - name: Use NTP to synchtonize the clock
      appliance_timesync:
        mode: NTP
...
