---
- name: deploy vm from template demo
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars-win.yml
  collections:
    - community.vmware
  tasks:
    - name: create folder
      vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter_name: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present
    - name: clone VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        template: "{{ vm_template }}"
        networks:
          - name: VM Network
            connected: true
            ip: 192.168.1.129
            netmask: 255.255.255.0
            gateway: 192.168.1.253
            dns_servers:
            - 192.168.1.178
        customization:
          autologon: true
          dns_servers:
            - 192.168.1.178
            - 8.8.8.8
          password: IPCom123.
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      delegate_to: localhost
...
