---
- name: create snaphot vm
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  vars_files:
    - vars-1.yml
  tasks:
    - name: create snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item }}"
        state: present
        snapshot_name: " {{ snap_name }}"
        #vcenter_destination_folder: "myvm-ansible-template"
        folder: "{{ vm_folder }}"
        description: "This snapshot is created by Ansible Playbook"
      with_items: "{{ vm_name }}" 
...
